export const AUTH_LOADING="AUTH_LOADING";
export const AUTH_ERROR ="AUTH_ERROR";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_CLEAR="AUTH_CLEAR";
export const AUTH_RESET_LOADING="AUTH_RESET_LOADING";